# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
#src: https://www.andreasnesheim.no/setting-up-ci-for-your-net-maui-ios-app-with-github-actions/

name: Release iOS

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Put distribution cert
        env: # Or as an environment variable
          APPLE_DISTRIBUTION_CERT_P12_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERT_P12_BASE64 }}
        run: echo "${APPLE_DISTRIBUTION_CERT_P12_BASE64}" | base64 -d > liftlog.p12
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-filepath: "liftlog.p12"
          p12-password: ${{ secrets.APPLE_DISTRIBUTION_CERT_PASS }}
      - name: Download Apple Provisioning Profiles
        id: provision
        uses: Apple-Actions/download-provisioning-profiles@v2
        with:
          bundle-id: "com.limajuice.liftlog"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      - name: Setup MAUI
        run: dotnet workload install maui
      - name: Build Tailwind
        run: yarn && yarn build
        working-directory: ./LiftLog.Ui
      - name: Build
        run: 'dotnet publish -c Release -f:net7.0-ios -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="${{ secrets.APPLE_CODESIGN_KEY_NAME }}" -p:CodesignProvision="LiftLog"'
        working-directory: ./LiftLog.App
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: "LiftLog.App/bin/Release/net7.0-ios/ios-arm64/publish/LiftLog.App.ipa"
          retention-days: 1
