# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
#src: https://www.andreasnesheim.no/setting-up-ci-for-your-net-maui-ios-app-with-github-actions/

name: Build iOS

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      KEYCHAIN: job-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Setup MAUI
        run: dotnet workload install maui
      - name: Build Tailwind
        run: yarn && yarn build
        working-directory: ./LiftLog.Ui
      - name: Build
        run: "dotnet build -f:net7.0-ios -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64"
        working-directory: ./LiftLog.App
