# Use github actions to Build our static website and upload to azure storage

name: Secrets
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF > .env
          APPLE_DISTRIBUTION_CERT_P12_BASE64={{secrets.APPLE_DISTRIBUTION_CERT_P12_BASE64}}
          APPLE_DISTRIBUTION_CERT_PASS={{secrets.APPLE_DISTRIBUTION_CERT_PASS}}
          APPSTORE_ISSUER_ID={{secrets.APPSTORE_ISSUER_ID}}
          APPSTORE_KEY_ID={{secrets.APPSTORE_KEY_ID}}
          APPSTORE_PRIVATE_KEY={{secrets.APPSTORE_PRIVATE_KEY}}
          APPLE_CODESIGN_KEY_NAME={{secrets.APPLE_CODESIGN_KEY_NAME}}
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON={{secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON}}
          ANDROID_KEYSTORE_PASS={{secrets.ANDROID_KEYSTORE_PASS}}
          ANDROID_KEYSTORE_BASE64={{secrets.ANDROID_KEYSTORE_BASE64}}
          EOF
      - uses: actions/upload-artifact@v2
        with:
          name: .env
          path: .env
