# Use github actions to Build our static website and upload to azure storage

name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
    paths:
      - "site/**"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
        working-directory: ./site
      - name: Build
        run: yarn build
        working-directory: ./site
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./site
          container_name: static-assets
          connection_string: ${{ secrets.AzureStaticSiteConnectionString }}
          extra_args: "--pattern css/app.min.css"
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: "true"
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./site
          container_name: static-assets
          connection_string: ${{ secrets.AzureStaticSiteConnectionString }}
          extra_args: "--pattern *.html"
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: "true"
