name: Upload site as docker image to ghcr.io
on:
  push:
    branches:
      - main
    paths:
      - "site/**"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn install
        working-directory: ./site
      - name: Build
        run: yarn build
        working-directory: ./site
      - name: Build Docker image
        run: docker build -t ghcr.io/liammorrow/liftlog:site .
      - name: Push Docker image
        run: docker push ghcr.io/liammorrow/liftlog:site
